In [39]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,LabelEncoder ,OneHotEncoder
import pickle

In [40]:
data = pd.read_csv('./Dataset/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

### Preprocessing the data

In [41]:
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)

#### Encode categorical Variable

In [42]:
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

#### One Hot Encode Geography

In [43]:
onehot_encoder_geography = OneHotEncoder()
geo_encoded = onehot_encoder_geography.fit_transform(data[['Geography']])
geo_encoded_df = pd.DataFrame(geo_encoded.toarray(), columns=onehot_encoder_geography.get_feature_names_out(['Geography']))

Combining The columns with original

In [44]:
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [45]:
#spilting the data into train and test
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [47]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [48]:
#Save the preprocessor objects
with open('label_encoder_gender.pkl', 'wb') as f:
    pickle.dump(label_encoder_gender, f)

with open('onehot_encoder_geography.pkl', 'wb') as f:
    pickle.dump(onehot_encoder_geography, f)    

with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)

### Train ANN Regression Problem Statement

In [49]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [50]:
#Building the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train_scaled.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression
])

##Compile the model
model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [51]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

log_dir = "Regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [52]:
## Set early stopping
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights = True)

In [53]:
##Train the model
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2, callbacks=[early_stopping, tensorboard_callback])

Epoch 1/100
200/200 [==============================] - 1s 4ms/step - loss: 13310886912.0000 - mean_absolute_error: 99991.5781 - val_loss: 13706214400.0000 - val_mean_absolute_error: 102078.8906
Epoch 2/100
200/200 [==============================] - 1s 3ms/step - loss: 13268410368.0000 - mean_absolute_error: 99779.2031 - val_loss: 13616062464.0000 - val_mean_absolute_error: 101637.5469
Epoch 3/100
200/200 [==============================] - 1s 3ms/step - loss: 13106580480.0000 - mean_absolute_error: 98972.5312 - val_loss: 13366258688.0000 - val_mean_absolute_error: 100419.6328
Epoch 4/100
200/200 [==============================] - 1s 3ms/step - loss: 12758453248.0000 - mean_absolute_error: 97238.0938 - val_loss: 12903359488.0000 - val_mean_absolute_error: 98159.5312
Epoch 5/100
200/200 [==============================] - 1s 3ms/step - loss: 12186471424.0000 - mean_absolute_error: 94400.6875 - val_loss: 12203955200.0000 - val_mean_absolute_error: 94744.3828
Epoch 6/100
200/200 [==============================] - 1s 3ms/step - loss: 11382796288.0000 - mean_absolute_error: 90398.0469 - val_loss: 11277443072.0000 - val_mean_absolute_error: 90181.9609
Epoch 7/100
200/200 [==============================] - 1s 3ms/step - loss: 10378085376.0000 - mean_absolute_error: 85409.3203 - val_loss: 10170813440.0000 - val_mean_absolute_error: 84699.7109
Epoch 8/100
200/200 [==============================] - 1s 3ms/step - loss: 9233887232.0000 - mean_absolute_error: 79697.1016 - val_loss: 8956241920.0000 - val_mean_absolute_error: 78625.9375
Epoch 9/100
200/200 [==============================] - 1s 3ms/step - loss: 8032402944.0000 - mean_absolute_error: 73610.8672 - val_loss: 7728192512.0000 - val_mean_absolute_error: 72439.2734
Epoch 10/100
200/200 [==============================] - 1s 3ms/step - loss: 6867901952.0000 - mean_absolute_error: 67755.9688 - val_loss: 6569428992.0000 - val_mean_absolute_error: 66520.1953
Epoch 11/100
200/200 [==============================] - 1s 3ms/step - loss: 5826356736.0000 - mean_absolute_error: 62502.0117 - val_loss: 5569571840.0000 - val_mean_absolute_error: 61302.7109
Epoch 12/100
200/200 [==============================] - 0s 2ms/step - loss: 4971393024.0000 - mean_absolute_error: 58032.6641 - val_loss: 4779815936.0000 - val_mean_absolute_error: 57137.4453
Epoch 13/100
200/200 [==============================] - 1s 3ms/step - loss: 4335517184.0000 - mean_absolute_error: 54804.6562 - val_loss: 4211081472.0000 - val_mean_absolute_error: 54110.9453
Epoch 14/100
200/200 [==============================] - 0s 2ms/step - loss: 3909274112.0000 - mean_absolute_error: 52624.4414 - val_loss: 3841220864.0000 - val_mean_absolute_error: 52076.1133
Epoch 15/100
200/200 [==============================] - 1s 3ms/step - loss: 3652378880.0000 - mean_absolute_error: 51267.0391 - val_loss: 3618893568.0000 - val_mean_absolute_error: 50862.3945
Epoch 16/100
200/200 [==============================] - 1s 3ms/step - loss: 3514012160.0000 - mean_absolute_error: 50575.4219 - val_loss: 3499545600.0000 - val_mean_absolute_error: 50226.7500
Epoch 17/100
200/200 [==============================] - 1s 3ms/step - loss: 3443976192.0000 - mean_absolute_error: 50221.5000 - val_loss: 3437294592.0000 - val_mean_absolute_error: 49901.1016
Epoch 18/100
200/200 [==============================] - 0s 2ms/step - loss: 3409223936.0000 - mean_absolute_error: 50071.6484 - val_loss: 3403910144.0000 - val_mean_absolute_error: 49751.3906
Epoch 19/100
200/200 [==============================] - 1s 3ms/step - loss: 3390756864.0000 - mean_absolute_error: 49984.9258 - val_loss: 3384278272.0000 - val_mean_absolute_error: 49674.9336
Epoch 20/100
200/200 [==============================] - 1s 3ms/step - loss: 3379312384.0000 - mean_absolute_error: 49935.9062 - val_loss: 3371435520.0000 - val_mean_absolute_error: 49623.7383
Epoch 21/100
200/200 [==============================] - 1s 3ms/step - loss: 3370865664.0000 - mean_absolute_error: 49895.4805 - val_loss: 3363532544.0000 - val_mean_absolute_error: 49593.6719
Epoch 22/100
200/200 [==============================] - 0s 2ms/step - loss: 3364076288.0000 - mean_absolute_error: 49868.9453 - val_loss: 3357007616.0000 - val_mean_absolute_error: 49566.1016
Epoch 23/100
200/200 [==============================] - 1s 3ms/step - loss: 3358525440.0000 - mean_absolute_error: 49844.1797 - val_loss: 3352005632.0000 - val_mean_absolute_error: 49548.6602
Epoch 24/100
200/200 [==============================] - 1s 3ms/step - loss: 3353379840.0000 - mean_absolute_error: 49821.3203 - val_loss: 3347458304.0000 - val_mean_absolute_error: 49535.1211
Epoch 25/100
200/200 [==============================] - 0s 2ms/step - loss: 3348698880.0000 - mean_absolute_error: 49799.7188 - val_loss: 3344226816.0000 - val_mean_absolute_error: 49524.7148
Epoch 26/100
200/200 [==============================] - 1s 3ms/step - loss: 3345202944.0000 - mean_absolute_error: 49787.4531 - val_loss: 3340882176.0000 - val_mean_absolute_error: 49511.8906
Epoch 27/100
200/200 [==============================] - 0s 2ms/step - loss: 3341675776.0000 - mean_absolute_error: 49763.9805 - val_loss: 3337899264.0000 - val_mean_absolute_error: 49502.5352
Epoch 28/100
200/200 [==============================] - 0s 2ms/step - loss: 3338233088.0000 - mean_absolute_error: 49752.3867 - val_loss: 3335416064.0000 - val_mean_absolute_error: 49495.6641
Epoch 29/100
200/200 [==============================] - 1s 3ms/step - loss: 3335446272.0000 - mean_absolute_error: 49736.5859 - val_loss: 3333845504.0000 - val_mean_absolute_error: 49494.0703
Epoch 30/100
200/200 [==============================] - 1s 3ms/step - loss: 3332378880.0000 - mean_absolute_error: 49720.5586 - val_loss: 3332197376.0000 - val_mean_absolute_error: 49491.0664
Epoch 31/100
200/200 [==============================] - 1s 3ms/step - loss: 3329972736.0000 - mean_absolute_error: 49708.6406 - val_loss: 3330544384.0000 - val_mean_absolute_error: 49488.9688
Epoch 32/100
200/200 [==============================] - 1s 3ms/step - loss: 3327852800.0000 - mean_absolute_error: 49696.4453 - val_loss: 3329219584.0000 - val_mean_absolute_error: 49487.0781
Epoch 33/100
200/200 [==============================] - 1s 3ms/step - loss: 3325625088.0000 - mean_absolute_error: 49685.2305 - val_loss: 3327673344.0000 - val_mean_absolute_error: 49484.8984
Epoch 34/100
200/200 [==============================] - 1s 3ms/step - loss: 3323628032.0000 - mean_absolute_error: 49675.1211 - val_loss: 3327440384.0000 - val_mean_absolute_error: 49486.0508
Epoch 35/100
200/200 [==============================] - 1s 3ms/step - loss: 3322002176.0000 - mean_absolute_error: 49663.9844 - val_loss: 3325912576.0000 - val_mean_absolute_error: 49482.2344
Epoch 36/100
200/200 [==============================] - 0s 2ms/step - loss: 3320704768.0000 - mean_absolute_error: 49656.8984 - val_loss: 3323866368.0000 - val_mean_absolute_error: 49478.9648
Epoch 37/100
200/200 [==============================] - 0s 2ms/step - loss: 3318859008.0000 - mean_absolute_error: 49644.6250 - val_loss: 3322215680.0000 - val_mean_absolute_error: 49473.7695
Epoch 38/100
200/200 [==============================] - 1s 3ms/step - loss: 3317115136.0000 - mean_absolute_error: 49634.6016 - val_loss: 3323116544.0000 - val_mean_absolute_error: 49477.9688
Epoch 39/100
200/200 [==============================] - 1s 3ms/step - loss: 3315977984.0000 - mean_absolute_error: 49627.4102 - val_loss: 3322449664.0000 - val_mean_absolute_error: 49478.3047
Epoch 40/100
200/200 [==============================] - 1s 3ms/step - loss: 3314809344.0000 - mean_absolute_error: 49621.6055 - val_loss: 3321875968.0000 - val_mean_absolute_error: 49478.1250
Epoch 41/100
200/200 [==============================] - 1s 3ms/step - loss: 3313611264.0000 - mean_absolute_error: 49615.2852 - val_loss: 3321242368.0000 - val_mean_absolute_error: 49475.6719
Epoch 42/100
200/200 [==============================] - 1s 3ms/step - loss: 3312148224.0000 - mean_absolute_error: 49602.7812 - val_loss: 3321017856.0000 - val_mean_absolute_error: 49477.0391
Epoch 43/100
200/200 [==============================] - 0s 2ms/step - loss: 3311179776.0000 - mean_absolute_error: 49596.8984 - val_loss: 3319543552.0000 - val_mean_absolute_error: 49472.6406
Epoch 44/100
200/200 [==============================] - 0s 2ms/step - loss: 3310123008.0000 - mean_absolute_error: 49590.3789 - val_loss: 3318657280.0000 - val_mean_absolute_error: 49470.0859
Epoch 45/100
200/200 [==============================] - 1s 3ms/step - loss: 3308962560.0000 - mean_absolute_error: 49582.3047 - val_loss: 3318531072.0000 - val_mean_absolute_error: 49472.2891
Epoch 46/100
200/200 [==============================] - 0s 2ms/step - loss: 3308315648.0000 - mean_absolute_error: 49577.4062 - val_loss: 3318330112.0000 - val_mean_absolute_error: 49473.6602
Epoch 47/100
200/200 [==============================] - 1s 3ms/step - loss: 3306947584.0000 - mean_absolute_error: 49568.9062 - val_loss: 3317407744.0000 - val_mean_absolute_error: 49470.9609
Epoch 48/100
200/200 [==============================] - 0s 2ms/step - loss: 3306336512.0000 - mean_absolute_error: 49562.5586 - val_loss: 3317437952.0000 - val_mean_absolute_error: 49470.8516
Epoch 49/100
200/200 [==============================] - 0s 2ms/step - loss: 3305576192.0000 - mean_absolute_error: 49561.5547 - val_loss: 3317078784.0000 - val_mean_absolute_error: 49471.6094
Epoch 50/100
200/200 [==============================] - 1s 3ms/step - loss: 3304460544.0000 - mean_absolute_error: 49549.9102 - val_loss: 3317067008.0000 - val_mean_absolute_error: 49472.8281
Epoch 51/100
200/200 [==============================] - 1s 3ms/step - loss: 3303710720.0000 - mean_absolute_error: 49542.7188 - val_loss: 3316412928.0000 - val_mean_absolute_error: 49471.7734
Epoch 52/100
200/200 [==============================] - 1s 4ms/step - loss: 3302858752.0000 - mean_absolute_error: 49537.9297 - val_loss: 3315740416.0000 - val_mean_absolute_error: 49471.2734
Epoch 53/100
200/200 [==============================] - 1s 4ms/step - loss: 3302307328.0000 - mean_absolute_error: 49534.3789 - val_loss: 3316505088.0000 - val_mean_absolute_error: 49475.1836
Epoch 54/100
200/200 [==============================] - 1s 3ms/step - loss: 3301586944.0000 - mean_absolute_error: 49525.5664 - val_loss: 3315865088.0000 - val_mean_absolute_error: 49472.6992
Epoch 55/100
200/200 [==============================] - 1s 3ms/step - loss: 3300741632.0000 - mean_absolute_error: 49521.9648 - val_loss: 3315641856.0000 - val_mean_absolute_error: 49473.9531
Epoch 56/100
200/200 [==============================] - 1s 3ms/step - loss: 3300367616.0000 - mean_absolute_error: 49517.7852 - val_loss: 3315230720.0000 - val_mean_absolute_error: 49473.7891
Epoch 57/100
200/200 [==============================] - 1s 3ms/step - loss: 3299877120.0000 - mean_absolute_error: 49516.8594 - val_loss: 3314802432.0000 - val_mean_absolute_error: 49474.6133
Epoch 58/100
200/200 [==============================] - 1s 3ms/step - loss: 3298833408.0000 - mean_absolute_error: 49503.5547 - val_loss: 3314493952.0000 - val_mean_absolute_error: 49474.1367
Epoch 59/100
200/200 [==============================] - 1s 3ms/step - loss: 3298424832.0000 - mean_absolute_error: 49504.2617 - val_loss: 3314457344.0000 - val_mean_absolute_error: 49473.2109
Epoch 60/100
200/200 [==============================] - 1s 3ms/step - loss: 3297910784.0000 - mean_absolute_error: 49498.7969 - val_loss: 3315030016.0000 - val_mean_absolute_error: 49475.1758
Epoch 61/100
200/200 [==============================] - 1s 3ms/step - loss: 3297250304.0000 - mean_absolute_error: 49492.1367 - val_loss: 3315431424.0000 - val_mean_absolute_error: 49478.2344
Epoch 62/100
200/200 [==============================] - 1s 4ms/step - loss: 3296622592.0000 - mean_absolute_error: 49488.2031 - val_loss: 3313983744.0000 - val_mean_absolute_error: 49472.9453
Epoch 63/100
200/200 [==============================] - 1s 3ms/step - loss: 3296248064.0000 - mean_absolute_error: 49486.5703 - val_loss: 3314318592.0000 - val_mean_absolute_error: 49475.8398
Epoch 64/100
200/200 [==============================] - 1s 3ms/step - loss: 3295613440.0000 - mean_absolute_error: 49480.2812 - val_loss: 3313925888.0000 - val_mean_absolute_error: 49474.7734
Epoch 65/100
200/200 [==============================] - 1s 3ms/step - loss: 3295399424.0000 - mean_absolute_error: 49479.1211 - val_loss: 3314100480.0000 - val_mean_absolute_error: 49478.9492
Epoch 66/100
200/200 [==============================] - 1s 4ms/step - loss: 3294891008.0000 - mean_absolute_error: 49474.0898 - val_loss: 3314519808.0000 - val_mean_absolute_error: 49478.4219
Epoch 67/100
200/200 [==============================] - 1s 3ms/step - loss: 3294241536.0000 - mean_absolute_error: 49468.0234 - val_loss: 3313820672.0000 - val_mean_absolute_error: 49477.5234
Epoch 68/100
200/200 [==============================] - 1s 3ms/step - loss: 3293794816.0000 - mean_absolute_error: 49467.3008 - val_loss: 3313379584.0000 - val_mean_absolute_error: 49478.5195
Epoch 69/100
200/200 [==============================] - 1s 3ms/step - loss: 3293303040.0000 - mean_absolute_error: 49461.5039 - val_loss: 3312803840.0000 - val_mean_absolute_error: 49475.3867
Epoch 70/100
200/200 [==============================] - 1s 4ms/step - loss: 3292797696.0000 - mean_absolute_error: 49459.0742 - val_loss: 3313336064.0000 - val_mean_absolute_error: 49479.2539
Epoch 71/100
200/200 [==============================] - 0s 2ms/step - loss: 3292513280.0000 - mean_absolute_error: 49454.8711 - val_loss: 3312599040.0000 - val_mean_absolute_error: 49477.1953
Epoch 72/100
200/200 [==============================] - 1s 3ms/step - loss: 3292104704.0000 - mean_absolute_error: 49451.5391 - val_loss: 3312797952.0000 - val_mean_absolute_error: 49477.7852
Epoch 73/100
200/200 [==============================] - 1s 4ms/step - loss: 3291711488.0000 - mean_absolute_error: 49448.7734 - val_loss: 3312358400.0000 - val_mean_absolute_error: 49477.5469
Epoch 74/100
200/200 [==============================] - 1s 4ms/step - loss: 3291139328.0000 - mean_absolute_error: 49443.6836 - val_loss: 3312270592.0000 - val_mean_absolute_error: 49477.8164
Epoch 75/100
200/200 [==============================] - 1s 3ms/step - loss: 3290700800.0000 - mean_absolute_error: 49437.8242 - val_loss: 3312276480.0000 - val_mean_absolute_error: 49478.7344
Epoch 76/100
200/200 [==============================] - 1s 3ms/step - loss: 3290557952.0000 - mean_absolute_error: 49438.3359 - val_loss: 3311886080.0000 - val_mean_absolute_error: 49476.8398
Epoch 77/100
200/200 [==============================] - 1s 3ms/step - loss: 3290194176.0000 - mean_absolute_error: 49434.1133 - val_loss: 3312042752.0000 - val_mean_absolute_error: 49476.6211
Epoch 78/100
200/200 [==============================] - 1s 4ms/step - loss: 3289492992.0000 - mean_absolute_error: 49432.6055 - val_loss: 3312392960.0000 - val_mean_absolute_error: 49478.6758
Epoch 79/100
200/200 [==============================] - 1s 3ms/step - loss: 3289443584.0000 - mean_absolute_error: 49433.4883 - val_loss: 3312568320.0000 - val_mean_absolute_error: 49480.5156
Epoch 80/100
200/200 [==============================] - 1s 4ms/step - loss: 3289225728.0000 - mean_absolute_error: 49430.2461 - val_loss: 3311813632.0000 - val_mean_absolute_error: 49478.5508
Epoch 81/100
200/200 [==============================] - 1s 4ms/step - loss: 3288804352.0000 - mean_absolute_error: 49427.9219 - val_loss: 3312147200.0000 - val_mean_absolute_error: 49479.9102
Epoch 82/100
200/200 [==============================] - 1s 3ms/step - loss: 3288553472.0000 - mean_absolute_error: 49422.6250 - val_loss: 3311405568.0000 - val_mean_absolute_error: 49478.2891
Epoch 83/100
200/200 [==============================] - 1s 3ms/step - loss: 3288046336.0000 - mean_absolute_error: 49417.4805 - val_loss: 3312252928.0000 - val_mean_absolute_error: 49482.7031
Epoch 84/100
200/200 [==============================] - 1s 3ms/step - loss: 3287522048.0000 - mean_absolute_error: 49417.8047 - val_loss: 3312098560.0000 - val_mean_absolute_error: 49480.8516
Epoch 85/100
200/200 [==============================] - 1s 3ms/step - loss: 3287236352.0000 - mean_absolute_error: 49413.1562 - val_loss: 3312227072.0000 - val_mean_absolute_error: 49482.0703
Epoch 86/100
200/200 [==============================] - 1s 3ms/step - loss: 3286813952.0000 - mean_absolute_error: 49409.2891 - val_loss: 3311754496.0000 - val_mean_absolute_error: 49482.5156
Epoch 87/100
200/200 [==============================] - 1s 4ms/step - loss: 3286494976.0000 - mean_absolute_error: 49410.6289 - val_loss: 3311340800.0000 - val_mean_absolute_error: 49483.4336
Epoch 88/100
200/200 [==============================] - 1s 3ms/step - loss: 3286262016.0000 - mean_absolute_error: 49404.3867 - val_loss: 3312079616.0000 - val_mean_absolute_error: 49483.2852
Epoch 89/100
200/200 [==============================] - 1s 3ms/step - loss: 3285846016.0000 - mean_absolute_error: 49399.3516 - val_loss: 3312082688.0000 - val_mean_absolute_error: 49484.8047
Epoch 90/100
200/200 [==============================] - 1s 3ms/step - loss: 3285634560.0000 - mean_absolute_error: 49396.7734 - val_loss: 3311956224.0000 - val_mean_absolute_error: 49483.5586
Epoch 91/100
200/200 [==============================] - 1s 3ms/step - loss: 3285347840.0000 - mean_absolute_error: 49397.0352 - val_loss: 3312915456.0000 - val_mean_absolute_error: 49488.2734
Epoch 92/100
200/200 [==============================] - 1s 3ms/step - loss: 3285030656.0000 - mean_absolute_error: 49394.8398 - val_loss: 3311538944.0000 - val_mean_absolute_error: 49483.8594
Epoch 93/100
200/200 [==============================] - 1s 3ms/step - loss: 3284877312.0000 - mean_absolute_error: 49395.8594 - val_loss: 3311355904.0000 - val_mean_absolute_error: 49482.7188
Epoch 94/100
200/200 [==============================] - 1s 3ms/step - loss: 3284739072.0000 - mean_absolute_error: 49393.4844 - val_loss: 3312589568.0000 - val_mean_absolute_error: 49488.8281
Epoch 95/100
200/200 [==============================] - 1s 3ms/step - loss: 3284024320.0000 - mean_absolute_error: 49387.1602 - val_loss: 3312022272.0000 - val_mean_absolute_error: 49488.3047
Epoch 96/100
200/200 [==============================] - 1s 3ms/step - loss: 3283854592.0000 - mean_absolute_error: 49385.1602 - val_loss: 3311563264.0000 - val_mean_absolute_error: 49486.8906
Epoch 97/100
200/200 [==============================] - 1s 4ms/step - loss: 3283586816.0000 - mean_absolute_error: 49382.6992 - val_loss: 3311145216.0000 - val_mean_absolute_error: 49485.2500
Epoch 98/100
200/200 [==============================] - 1s 3ms/step - loss: 3283713792.0000 - mean_absolute_error: 49384.9102 - val_loss: 3311976192.0000 - val_mean_absolute_error: 49488.0781
Epoch 99/100
200/200 [==============================] - 1s 3ms/step - loss: 3283224832.0000 - mean_absolute_error: 49381.7148 - val_loss: 3311216640.0000 - val_mean_absolute_error: 49486.9062
Epoch 100/100
200/200 [==============================] - 1s 3ms/step - loss: 3283236608.0000 - mean_absolute_error: 49381.1250 - val_loss: 3310140672.0000 - val_mean_absolute_error: 49482.8594

In [54]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 17728), started 7:41:36 ago. (Use '!kill 17728' to kill it.)

In [55]:
## Evaluate the model
test_loss, test_mae = model.evaluate(X_test_scaled, y_test)
print(f'Test Loss: {test_loss}, Test MAE: {test_mae}')

63/63 [==============================] - 0s 2ms/step - loss: 3357463296.0000 - mean_absolute_error: 50069.6250
Test Loss: 3357463296.0, Test MAE: 50069.625

In [56]:
model.save('salary_regression_model.h5')

c:\Users\samya\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(